name: Android CI

on:
  pull_request:
    branches:
    - development

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Set up Ruby 3.1
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.1.x
    - name: Update Fastlane
      run: |
        bundle install
        bundle exec fastlane -v
    - name: Download secrets
      env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
         scripts/download_s3.sh gradle.properties > gradle.properties
         scripts/download_s3.sh google-services.json > app/google-services.json
    - name: Run Tests
      run: bundle exec fastlane test

